on:
  push:
    tags:
      - 'v*'

name: Create Lambda Release Artefacts

jobs:
  build:
    name: Create Lambda Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install brew packages
        run: sudo apt-get install build-essential curl file git

      - name: Install homebrew
        run: |
          git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
          mkdir ~/.linuxbrew/bin
          ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin
          eval $(~/.linuxbrew/bin/brew shellenv)

      - name: Install sam
        run: |
          brew tap aws/tap
          brew install aws-sam-cli

      - name: Build project
        run: |
          npm ci
          npm run-script build
          sam build --use-container

      - name: Zip images
        working-directory: .aws-sam/build
        run: |
          readarray -t lambda_dirs <<< "$(find . -maxdepth 1 -mindepth 1 -type d)"
          for dir in "${lambda_dirs[@]}"; do
            export dir="${dir}"
            ( cd "${dir}" && zip -r "../${dir/'./'/''}" ./ )
          done

      - name: Create Tag Release
        id: create_tag_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref  }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - id: get-tag-name
        run: |
          tag_ref="${{github.ref}}"
          tag_name=$(echo "${tag_ref##*/}"" )
          echo "::set-output name=tag_name::$tag_name"

      - name: Upload Tag Release Asset
        id: upload_tag_release_assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: '.aws-sam/build/*.zip'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{steps.get-tag-name.outputs.tag_name}}
